repository: sophshep/manager-resources

sass:
  load_paths:
    - node_modules

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

topics:
  - name: Web design

  - name: CSS
    github_name: css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Sass
    github_name: sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
