repository: sophshep/manager-resources

sass:
  sass_dir: node_modules

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

topics:
  - name: Web design
    github_name: web-design
  - name: CSS
    github_name: css
  - name: Sass
    github_name: sass
